package ru.logunov.bydsplit;
import android.content.Context;
import org.json.*;
import java.util.*;
final class AutomationStore {
 static String key(CameraPlace p){return p.name+"|"+p.latitude+"|"+p.longitude;}
 static List<TemperatureRules.Rule> load(Context c){List<TemperatureRules.Rule> rules=new ArrayList<>();try{JSONArray list=new JSONArray(c.getSharedPreferences("temperature_automation",0).getString("rules","[]"));for(int i=0;i<list.length();i++){JSONObject o=list.getJSONObject(i);TemperatureRules.Rule r=new TemperatureRules.Rule();r.id=o.getString("id");r.name=o.getString("name");r.enabled=o.getBoolean("enabled");r.below=o.optBoolean("below",true);r.threshold=(float)o.optDouble("threshold",5);r.all=o.optBoolean("all",true);r.startupOnly=o.optBoolean("startupOnly",false);JSONArray durations=o.optJSONArray("durations");if(durations!=null)for(int a=0;a<Math.min(6,durations.length());a++)r.durationMinutes[a]=durations.optInt(a,0);JSONArray cs=o.optJSONArray("conditions");if(cs!=null)for(int j=0;j<cs.length();j++){JSONObject co=cs.getJSONObject(j);TemperatureRules.Condition condition=new TemperatureRules.Condition(co.optBoolean("below",true),(float)co.optDouble("threshold",5));condition.cabin=co.optBoolean("cabin",false);condition.placeKey=co.has("place")?co.getString("place"):null;r.conditions.add(condition);}JSONArray levels=o.getJSONArray("levels");for(int a=0;a<Math.min(levels.length(),6);a++)r.levels[a]=levels.getInt(a);rules.add(r);}}catch(JSONException e){android.util.Log.e("AutomationStore","Load failed",e);}return rules;}
 static void save(Context c,List<TemperatureRules.Rule> rules){JSONArray list=new JSONArray();try{for(TemperatureRules.Rule r:rules){JSONObject o=new JSONObject();o.put("id",r.id);o.put("name",r.name);o.put("enabled",r.enabled);o.put("below",r.below);o.put("threshold",r.threshold);o.put("all",r.all);o.put("startupOnly",r.startupOnly);JSONArray durations=new JSONArray();for(int m:r.durationMinutes)durations.put(m);o.put("durations",durations);JSONArray cs=new JSONArray();for(TemperatureRules.Condition condition:r.conditions){JSONObject co=new JSONObject();co.put("below",condition.below);co.put("cabin",condition.cabin);co.put("threshold",condition.threshold);if(condition.placeKey!=null)co.put("place",condition.placeKey);cs.put(co);}o.put("conditions",cs);JSONArray levels=new JSONArray();for(int l:r.levels)levels.put(l);o.put("levels",levels);list.put(o);}}catch(JSONException e){throw new IllegalStateException(e);}c.getSharedPreferences("temperature_automation",0).edit().putString("rules",list.toString()).apply();}
 static boolean hasCameraRules(Context c){for(TemperatureRules.Rule r:load(c))if(r.enabled&&r.levels[5]>=0)return true;return false;}
}
